// Augment Express Request to carry the absolute disk path generated by multer
// for the CV file, *before* multer finishes writing it. This lets the global
// error handler clean up partial uploads when multer aborts mid-write (e.g.
// LIMIT_FILE_SIZE), case in which `req.file` is never populated.
declare global {
  namespace Express {
    interface Request {
      cvDiskPath?: string;
    }
  }
}

export {};
